FROM golang:1.25-bookworm AS builder

WORKDIR /app
COPY ./go.mod ./go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -ldflags="-s -w" -trimpath -o main .

FROM scratch

# バイナリを配置
COPY --from=builder /app/main /go-bin/main

# 非特権ユーザで実行
USER 10000

EXPOSE 80

CMD ["/go-bin/main"]
