package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"strings"

	"github.com/naoya0117/shuron2025/api/graph/model"
	"github.com/naoya0117/shuron2025/api/internal/database"
)

// CreateCheckResult is the resolver for the createCheckResult field.
func (r *mutationResolver) CreateCheckResult(ctx context.Context, input model.NewCheckResultInput) (*model.MutationResult, error) {
	repositoryID := int(input.RepositoryID)
	checkItemID := int(input.CheckItemID)

	if repositoryID <= 0 {
		return nil, fmt.Errorf("リポジトリIDが不正です")
	}
	if checkItemID <= 0 {
		return nil, fmt.Errorf("チェック項目IDが不正です")
	}

	var memoPtr *string
	if input.Memo != nil {
		memo := strings.TrimSpace(*input.Memo)
		if memo != "" {
			memoPtr = &memo
		}
	}

	if _, err := r.DB.CreateCheckResult(repositoryID, checkItemID, input.Result, memoPtr); err != nil {
		return nil, fmt.Errorf("チェック結果の保存に失敗しました: %w", err)
	}

	message := "チェック結果を登録しました"
	return &model.MutationResult{
		Success: true,
		Message: &message,
	}, nil
}

// UpdateCheckResult is the resolver for the updateCheckResult field.
func (r *mutationResolver) UpdateCheckResult(ctx context.Context, id int32, input model.NewCheckResultInput) (*model.MutationResult, error) {
	repositoryID := int(input.RepositoryID)
	checkItemID := int(input.CheckItemID)

	if repositoryID <= 0 {
		return nil, fmt.Errorf("リポジトリIDが不正です")
	}
	if checkItemID <= 0 {
		return nil, fmt.Errorf("チェック項目IDが不正です")
	}

	var memoPtr *string
	if input.Memo != nil {
		memo := strings.TrimSpace(*input.Memo)
		if memo != "" {
			memoPtr = &memo
		}
	}

	if err := r.DB.UpdateCheckResult(int(id), repositoryID, checkItemID, input.Result, memoPtr); err != nil {
		return nil, fmt.Errorf("チェック結果の更新に失敗しました: %w", err)
	}

	message := "チェック結果を更新しました"
	return &model.MutationResult{
		Success: true,
		Message: &message,
	}, nil
}

// DeleteCheckResult is the resolver for the deleteCheckResult field.
func (r *mutationResolver) DeleteCheckResult(ctx context.Context, id int32) (*model.MutationResult, error) {
	if err := r.DB.DeleteCheckResult(int(id)); err != nil {
		return nil, fmt.Errorf("チェック結果の削除に失敗しました: %w", err)
	}

	message := "チェック結果を削除しました"
	return &model.MutationResult{
		Success: true,
		Message: &message,
	}, nil
}

// AdminDashboard is the resolver for the adminDashboard field.
func (r *queryResolver) AdminDashboard(ctx context.Context, limit *int32) (*model.AdminDashboard, error) {
	l := 50
	if limit != nil && *limit > 0 {
		l = int(*limit)
	}

	patterns, err := r.DB.GetK8sPatterns()
	if err != nil {
		return nil, fmt.Errorf("パターン一覧の取得に失敗しました: %w", err)
	}

	repos, err := r.DB.GetRepositories(l, 0)
	if err != nil {
		return nil, fmt.Errorf("リポジトリ一覧の取得に失敗しました: %w", err)
	}

	checkResults, err := r.DB.GetCheckResults(nil)
	if err != nil {
		return nil, fmt.Errorf("チェック結果の取得に失敗しました: %w", err)
	}

	return &model.AdminDashboard{
		Patterns:     convertK8sPatterns(patterns),
		Repositories: convertRepositories(repos),
		CheckResults: convertCheckResults(checkResults),
	}, nil
}

// Patterns is the resolver for the patterns field.
func (r *queryResolver) Patterns(ctx context.Context) ([]*model.K8sPattern, error) {
	patterns, err := r.DB.GetK8sPatterns()
	if err != nil {
		return nil, fmt.Errorf("パターン一覧の取得に失敗しました: %w", err)
	}
	return convertK8sPatterns(patterns), nil
}

// CheckItems is the resolver for the checkItems field.
func (r *queryResolver) CheckItems(ctx context.Context, patternID *int32) ([]*model.CheckItem, error) {
	var patternIDPtr *int
	if patternID != nil {
		id := int(*patternID)
		patternIDPtr = &id
	}

	items, err := r.DB.GetCheckItems(patternIDPtr)
	if err != nil {
		return nil, fmt.Errorf("チェック項目の取得に失敗しました: %w", err)
	}
	return convertCheckItems(items), nil
}

// CheckResults is the resolver for the checkResults field.
func (r *queryResolver) CheckResults(ctx context.Context, repositoryID *int32) ([]*model.CheckResult, error) {
	var repositoryIDPtr *int
	if repositoryID != nil {
		id := int(*repositoryID)
		repositoryIDPtr = &id
	}

	results, err := r.DB.GetCheckResults(repositoryIDPtr)
	if err != nil {
		return nil, fmt.Errorf("チェック結果の取得に失敗しました: %w", err)
	}
	return convertCheckResults(results), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// Helper functions to convert database models to GraphQL models

func convertK8sPatterns(patterns []database.K8sPattern) []*model.K8sPattern {
	result := make([]*model.K8sPattern, 0, len(patterns))
	for _, p := range patterns {
		var description *string
		if p.Description != nil && strings.TrimSpace(*p.Description) != "" {
			desc := strings.TrimSpace(*p.Description)
			description = &desc
		}
		result = append(result, &model.K8sPattern{
			ID:          int32(p.ID),
			Name:        p.Name,
			Description: description,
			CreatedAt:   p.CreatedAt,
		})
	}
	return result
}

func convertCheckItems(items []database.CheckItem) []*model.CheckItem {
	result := make([]*model.CheckItem, 0, len(items))
	for _, item := range items {
		var description *string
		if item.Description != nil && strings.TrimSpace(*item.Description) != "" {
			desc := strings.TrimSpace(*item.Description)
			description = &desc
		}
		result = append(result, &model.CheckItem{
			ID:          int32(item.ID),
			PatternID:   int32(item.PatternID),
			Name:        item.Name,
			Description: description,
			CreatedAt:   item.CreatedAt,
		})
	}
	return result
}

func convertCheckResults(results []database.CheckResult) []*model.CheckResult {
	result := make([]*model.CheckResult, 0, len(results))
	for _, r := range results {
		var memo *string
		if r.Memo != nil && strings.TrimSpace(*r.Memo) != "" {
			m := strings.TrimSpace(*r.Memo)
			memo = &m
		}
		result = append(result, &model.CheckResult{
			ID:           int32(r.ID),
			RepositoryID: int32(r.RepositoryID),
			CheckItemID:  int32(r.CheckItemID),
			Result:       r.Result,
			Memo:         memo,
			CheckedAt:    r.CheckedAt,
			UpdatedAt:    r.UpdatedAt,
		})
	}
	return result
}

func convertRepositories(repos []database.Repository) []*model.Repository {
	result := make([]*model.Repository, 0, len(repos))
	for _, repo := range repos {
		var primaryLanguage *string
		if repo.PrimaryLanguage != nil && strings.TrimSpace(*repo.PrimaryLanguage) != "" {
			lang := strings.TrimSpace(*repo.PrimaryLanguage)
			primaryLanguage = &lang
		}
		result = append(result, &model.Repository{
			ID:              int32(repo.ID),
			NameWithOwner:   repo.NameWithOwner,
			StargazerCount:  int32(repo.StargazerCount),
			PrimaryLanguage: primaryLanguage,
			HasDockerfile:   repo.HasDockerfile,
			CreatedAt:       repo.CreatedAt,
		})
	}
	return result
}
