// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AdminDashboard struct {
	Patterns     []*K8sPattern  `json:"patterns"`
	Repositories []*Repository  `json:"repositories"`
	CheckResults []*CheckResult `json:"checkResults"`
}

type CheckItem struct {
	ID          int32       `json:"id"`
	PatternID   int32       `json:"patternId"`
	Pattern     *K8sPattern `json:"pattern"`
	Name        string      `json:"name"`
	Description *string     `json:"description,omitempty"`
	CreatedAt   time.Time   `json:"createdAt"`
}

type CheckResult struct {
	ID           int32       `json:"id"`
	RepositoryID int32       `json:"repositoryId"`
	Repository   *Repository `json:"repository"`
	CheckItemID  int32       `json:"checkItemId"`
	CheckItem    *CheckItem  `json:"checkItem"`
	Result       bool        `json:"result"`
	Memo         *string     `json:"memo,omitempty"`
	CheckedAt    time.Time   `json:"checkedAt"`
	UpdatedAt    time.Time   `json:"updatedAt"`
}

type K8sPattern struct {
	ID          int32        `json:"id"`
	Name        string       `json:"name"`
	Description *string      `json:"description,omitempty"`
	CheckItems  []*CheckItem `json:"checkItems"`
	CreatedAt   time.Time    `json:"createdAt"`
}

type Mutation struct {
}

type MutationResult struct {
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
}

type NewCheckResultInput struct {
	RepositoryID int32   `json:"repositoryId"`
	CheckItemID  int32   `json:"checkItemId"`
	Result       bool    `json:"result"`
	Memo         *string `json:"memo,omitempty"`
}

type Query struct {
}

type Repository struct {
	ID              int32     `json:"id"`
	NameWithOwner   string    `json:"nameWithOwner"`
	StargazerCount  int32     `json:"stargazerCount"`
	PrimaryLanguage *string   `json:"primaryLanguage,omitempty"`
	HasDockerfile   bool      `json:"hasDockerfile"`
	CreatedAt       time.Time `json:"createdAt"`
}
